add sessionId or executionError to action output

diff --git a/.github/workflows/create_session.yaml b/.github/workflows/create_session.yaml
--- a/.github/workflows/create_session.yaml
+++ b/.github/workflows/create_session.yaml
@@ -45,7 +45,31 @@ jobs:
           role-session-name: prompt-library-action
           aws-region: eu-west-1
       
-      - name: AWS CLI v2
-        uses: imehedi/actions-awscli-v2@latest
-        with:
-          args: stepfunctions start-execution --state-machine-arn ${{ env.TEST_SESSION_STATE_MACHINE_ARN }} --input "{\"time\":\"${{ env.NOW }}\",\"number_of_students\":1,\"prompt_version\":\"${{ env.BRANCH_NAME }}\",\"start_session\":${{ env.START_SESSION }},\"tutor_id\":${{ env.AI_TUTOR_ID }},\"school_id\":${{ github.event.inputs.school_id }},\"student_ids\":[${{ github.event.inputs.student_id }}],\"lesson_ids\":[${{ github.event.inputs.lesson_id }}]}"
+      - name: Start Step Function Execution
+        id: start_execution
+        run: |
+          result=$(aws stepfunctions start-execution --state-machine-arn ${{ env.TEST_SESSION_STATE_MACHINE_ARN }} --input "{\"time\":\"${{ env.NOW }}\",\"number_of_students\":1,\"prompt_version\":\"${{ env.BRANCH_NAME }}\",\"start_session\":\"${{ env.START_SESSION }}\",\"tutor_id\":${{ env.AI_TUTOR_ID }},\"school_id\":${{ github.event.inputs.school_id }},\"student_ids\":[${{ github.event.inputs.student_id }}],\"lesson_ids\":[${{ github.event.inputs.lesson_id }}]}")
+          executionArn=$(echo $result | jq -r '.executionArn')
+          echo "EXECUTION_ARN=$executionArn" >> $GITHUB_ENV
+          echo "::set-output name=executionArn::$executionArn"
+
+      - name: Wait for Execution Result
+        run: |
+          while true; do
+            executionResult=$(aws stepfunctions describe-execution --execution-arn ${{ env.EXECUTION_ARN }})
+            status=$(echo $executionResult | jq -r '.status')
+            if [[ $status == "SUCCEEDED" ]]; then
+              echo "Execution succeeded"
+              output=$(echo $executionResult | jq -r '.output[0].session.id')
+              echo "::set-output name=sessionId::$output"
+              break
+            elif [[ $status == "FAILED" ]]; then
+              echo "Execution failed"
+              output=$(echo $executionResult | jq -r '.cause')
+              echo "::set-output name=executionError::$output"
+              exit 1
+            else
+              echo "Waiting for execution to complete..."
+              sleep 5
+          fi
+          done
